# Generated by Django 4.0.5 on 2022-06-18 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('urgent', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('create', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Todoss',
        ),
    ]
